version: "3.9"
services:
  subversion:
    build: ./subversion
    ports:
    - 8080:80
    volumes:
      - cicd-vols:/var/www/svn
#  sap-ase:
#    image: sap-express:latest
#    ports:
#    - 5001:5000
#    volumes:
#    - cicd-vols:/opt/sap/data
volumes:
  cicd-vols:
