version: "3.9"
services:
  subversion:
    build: ./subversion
    ports:
      - 9080:80
    volumes:
      - svn-vol:/var/www/svn
  nexus:
    image: sonatype/nexus3:3.29.2
    ports:
      - 9081:8081
  sonarqube:
    image: sonarqube:8.6.1-community
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  sap-ase:
    image: sap-express:latest
    hostname: 127.0.0.1
    ports:
      - 9500:5000
  jboss:
    build: ./jboss
    ports:
      - 9800:8080
      - 9900:9990
  service-scripts:
    build: ./service-scripts
    tty: true
  jenkins:
    image: jenkins/jenkins:lts-slim
    ports:
      - 9888:8080
      - 50000:50000
    volumes:
      - jenkins-vol:/var/jenkins_home
  teamcity:
    image: jetbrains/teamcity-server:2020.2.2
    ports:
      - 8111:8111
    volumes:
      - teamcity-vol:/data/teamcity_server/datadir
      - teamcity-vol:/opt/teamcity/logs
  teamcity-agent:
    build: ./teamcity-agent
    environment:
      - SERVER_URL=http://teamcity:8111
    volumes:
      - teamcity-vol:/data/teamcity_agent/conf
    depends_on:
      - teamcity
volumes:
  svn-vol:
  jenkins-vol:
  teamcity-vol: