INSERT INTO movie (id, title, stream_count) values (1, 'Toy Story', 0)
INSERT INTO movie (id, title, stream_count) values (2, 'A Bugs Life', 0)
INSERT INTO movie (id, title, stream_count) values (3, 'Finding Nemo', 0)
INSERT INTO movie (id, title, stream_count) values (4, 'Wrecking Ralph', 0)
INSERT INTO movie (id, title, stream_count) values (5, 'Cars', 0)
INSERT INTO movie (id, title, stream_count) values (6, 'Brave', 0)
INSERT INTO movie (id, title, stream_count) values (7, 'Onward', 0)
INSERT INTO movie (id, title, stream_count) values (8, 'Ratatouille', 0)
INSERT INTO movie (id, title, stream_count) values (9, 'Inside Out', 0)
INSERT INTO movie (id, title, stream_count) values (10, 'Incredibles', 0)